### ISSUE TITLE
Mod Required for Other Players

### ISSUE THREAD

**Issue by WondaMegapon** [Flyingcomputer/ExchangeChanges-RoR2#1]
It's not much of a server-side mod if clients are also required to install it.

![image](https://user-images.githubusercontent.com/18584493/157765111-92bdff1f-c755-4395-8384-93f66b5706e1.png)

**Comment by Flyingcomputer** [comment]
This was just me misunderstanding what server-side meant, assumed if it worked multiplayer for all players it was server-side even if it required them to download the mod too. I've fixed the mod not letting clients connect without them having it and as far as i can tell it works for all players regardless of them having the mod downloaded so I believe the issue is solved
